import { hero } from './hero';

export const HEROES: hero[] = [
  {
    id: 11,
    name: 'Dr Nice',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 12,
    name: 'Narco',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 13,
    name: 'Bombasto',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 14,
    name: 'Celeritas',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 15,
    name: 'Magneta',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 16,
    name: 'RubberMan',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 17,
    name: 'Dynama',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 18,
    name: 'Dr IQ',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 19,
    name: 'Magma',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
  {
    id: 20,
    name: 'Tornado',
    health: 100,
    weapon: { id: 1, name: 'guns', damage: 100 },
    armour: { id: 1, name: 'shirt', health: 100 },
    imgSrc: '/assets/hero1.png',
  },
];
